routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\UserAPIController;
use \App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('users', [\App\Http\Controllers\UserController::class, 'index']);
Route::get('users', [\App\Http\Controllers\UserController::class, 'index']);*/
Route::get('get-users-api', [UserAPIController::class, 'getUsersAPI']);
Route::resource('users-api', UserAPIController::class);
Route::get('get-users', [UserController::class , 'getUsers'])->name('users.get-users');
Route::resource('users', UserController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserAPIController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class UserAPIController extends Controller
{
    public function index()
    {
        return view('user-api.index');
    }

    public function getUsersAPI(Request $request)
    {
        $users_1 = Http::get('https://reqres.in/api/users',  [
            'page' => 1,
        ]);
        $users_2 =  Http::get('https://reqres.in/api/users',  [
            'page' => 2,
        ]);
        $users_1 = $users_1->object()->data;
        $users_2 = $users_2->object()->data;

        $data = collect($users_1)->merge(collect($users_2));

        if(!empty($request->search)){
            return response()->json($data->where('id', '=', $request->search)->flatten());
        }
        return $data->toJson();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    public function index()
    {
        return view('user.index');
    }

    public function getUsers()
    {
        return User::all();
    }

    public function store(Request $request)
    {
        try{
            return response()->json([
                'status' => true,
                'data' => User::create($request->user)
            ]);
        }catch (\Exception $e){
            Log::error($e->getMessage());
            return response()->json(['status' => false, 'message' => 'Ocurrío un Error']);
        }

    }

    public function destroy($id)
    {
        try {
            return response()->json([
                'status' => true,
                'data' => User::find($id)->delete()
            ]);
        } catch (\Exception $e) {
            Log::error($e->getMessage());
            return response()->json(['status' => false, 'message' => 'Ocurrío un Error']);
        }
    }

}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">


    <main class="cpy-4 mt-5">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/user-api/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Listado de Usuarios</div>
                    <div class="card-body">
                        <users-api-component></users-api-component>
                        <a href="{{ route('users.index') }}" target="_blank">Ver Usuarios Registrados</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Listado de Usuarios Registrados</div>
                    <div class="card-body">
                        <users-component></users-component>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection